export const profile = {
  name: "Krishna",
  email: "krishnakumar.tech7@gmail.com",
  phone: "9873937564",
  location: "Greater Noida, Uttar Pradesh, India",
  github: "https://github.com/krishnak64",
  linkedin: "https://www.linkedin.com/in/krishnakumar", // TODO: verify your exact LinkedIn URL
  leetcode: "https://leetcode.com/u/krishna_123rt",
  gfg: "https://www.geeksforgeeks.org/profile/krishnad33g",
};
export const modes = {
  fs: { label: "Full Stack", line: "Builds full stack products people actually use.",
    about: "B.Tech IT student with a strong base in Java, DSA and OOP. I design and ship MERN applications with REST APIs, authentication, real-time features and third-party integrations, and I've deployed 6+ production-grade apps." },
  ai: { label: "AI/ML", line: "Builds AI apps that see, listen and reason.",
    about: "I combine backend engineering with LLM APIs, RAG pipelines and computer vision. From multi-agent LangGraph systems to real-time pose coaching and face + voice attendance, I take AI from notebook to a live URL." },
};
export const skills = {
  fs: [["Languages", "Java, JavaScript, Python"], ["Frontend", "React.js, Redux Toolkit, React Router, Tailwind CSS, Bootstrap, HTML5, CSS3, EJS"],
    ["Backend", "Node.js, Express.js, REST APIs, Socket.IO, JWT, bcrypt"], ["Databases", "MongoDB, MongoDB Atlas, SQL, MySQL, Redis"],
    ["Tools", "Git, GitHub, Docker, CI/CD, Render, Vercel, Netlify, AWS, Postman, Cloudinary, Firebase, Stripe"],
    ["Core", "DSA (350+ solved), OOP, System design basics"]],
  ai: [["Languages", "Python, Java"], ["GenAI", "LangChain, LangGraph, RAG, Embeddings, Vector DBs (Qdrant), OpenRouter, Groq API"],
    ["ML & Vision", "TensorFlow, PyTorch, Scikit-learn, Reinforcement Learning (DQN), PyTorch Geometric (GNNs), OpenCV, MediaPipe, dlib, face_recognition"],
    ["Data Science", "Pandas, NumPy, Statistics, EDA, Feature Engineering, Data Visualization (Matplotlib, Seaborn)"],
    ["Serving & Deployment", "FastAPI, Flask, Streamlit, Render, Docker, CI/CD, AWS, WebRTC"],
    ["Data stores", "SQL, MySQL, MongoDB, Qdrant, Redis, Supabase"]],
};
export const experience = [
  { role: "Software Engineer Intern", org: "Taskinterns Software", when: "Jun 2026 – Jul 2026",
    text: "Built a DSA Visualization app with React.js: interactive, step-by-step views of data structures and algorithms. Worked independently and alongside the Founder's Office." },
  { role: "AI/ML Virtual Intern", org: "Microsoft · Edunet Foundation · AICTE", when: "Apr 10 – May 10, 2025",
    text: "4-week industry-backed program on Foundations of AI: ML concepts and real-world application development with mentors and peers." },
];
export const projects = [
  { id: "cortex", featured: true, videoEmbed: "https://www.linkedin.com/embed/feed/update/urn:li:ugcPost:7508196879428374528?collapsed=1",  tags: ["fs", "ai"], name: "CORTEX AI — Multi-Agent Platform", live: "https://github.com/Krishnak64/Multi-Agent-AI-Platform-CortexAI-",
    blurb: "A production-ready multi-agent AI platform on the MERN stack with a microservices architecture. One prompt goes in, a router agent picks the right specialised agent, and the answer streams back.",
    features: ["8 specialised agents behind one router", "LangGraph routing and state management", "RAG: chat with your own PDFs using Qdrant", "Token-by-token streaming responses", "AI tool calling for external tools", "Microservices behind an API gateway", "JWT authentication", "Redis caching for speed and lower cost", "File upload and document processing", "Dockerized: one command runs everything", "Scalable folder structure, clean code"],
    stack: ["React.js", "Redux Toolkit", "Node.js", "Express.js", "LangGraph", "LangChain", "RAG", "MongoDB", "Qdrant", "Redis", "Docker"], repo: "https://github.com/Krishnak64/Multi-Agent-AI-Platform-CortexAI-" },
  { id: "builder", videoEmbed: "https://www.linkedin.com/embed/feed/update/urn:li:ugcPost:7484309148197900288?collapsed=1", tags: ["fs", "ai"], name: "MERN AI Website Builder", live: "https://websitebuilder-3p61.onrender.com/",
    blurb: "Describe a website in plain language and get working code you can edit in the browser.",
    features: ["OpenRouter API for code generation", "Monaco Editor for in-browser editing", "Firebase auth and storage, Stripe payments", "Express REST APIs, MongoDB schemas, deployed on Render"],
    stack: ["MongoDB", "Express", "React", "Node.js", "OpenRouter", "Firebase", "Stripe"], repo: "https://github.com/Krishnak64/WebSiteBuilder-" },
  { id: "examnotes", post: "https://www.linkedin.com/posts/krishna-kumar-5230b4300_excited-to-share-my-latest-project-examnotes-activity-7430296315479162880-UD71", tags: ["fs", "ai"], name: "ExamNotesAI — AI Exam Notes Generator", live: "https://examnotesaiclient-vl8k.onrender.com/",
    blurb: "Turn any topic into clear, exam-ready notes in seconds. Enter a subject and Google Gemini generates structured, easy-to-revise notes; Stripe unlocks premium usage.",
    features: ["AI-generated, well-structured notes powered by Google Gemini", "Stripe payments for credits and premium access", "Secure sign up and log in", "Topic-based generation for any subject", "Responsive on desktop, tablet and mobile", "Separate client and server, deployed on Render"],
    stack: ["React", "JavaScript", "Tailwind CSS", "Node.js", "Express.js", "MongoDB", "Google Gemini API", "Stripe", "Render"], repo: "https://github.com/Krishnak64/ExamNotesAI" },
  { id: "gym", videoEmbed: "https://www.linkedin.com/embed/feed/update/urn:li:ugcPost:7472608634925993984?collapsed=1", tags: ["ai"], name: "Real-Time AI Gym Coach", live: "https://ai-gym-coach-live.netlify.app/",
    blurb: "Webcam-based coach that counts reps, checks posture and talks you through the workout.",
    features: ["MediaPipe tracks 33 body landmarks live", "Groq LLM gives form corrections and motivation", "gTTS voice guidance, hands-free", "Streamlit UI, WebRTC video, Pandas session tracking"],
    stack: ["Python", "OpenCV", "MediaPipe", "Streamlit", "WebRTC", "Groq", "gTTS"], repo: "https://github.com/Krishnak64/RealTime-Voice-Video-AI-GYM-Trainer-Mediapipe" },
  { id: "snap", videoEmbed: "https://www.linkedin.com/embed/feed/update/urn:li:ugcPost:7465707139118911488?collapsed=1", tags: ["ai"], name: "SnapClass AI — Smart Attendance", live: "https://snapclass-ai-attendance-landing-pag.vercel.app/",
    blurb: "Attendance that verifies face, voice and QR code together, ending proxy attendance.",
    features: ["dlib + face_recognition for faces, librosa + resemblyzer for voice", "Supabase cloud database, real-time records", "bcrypt auth and dynamic QR codes with segno", "Cut manual attendance time by 80–90%"],
    stack: ["Python", "Streamlit", "dlib", "librosa", "resemblyzer", "Supabase"], repo: "https://github.com/Krishnak64/snapclass_ai-attendance-project" },
  { id: "videoassistant", videoEmbed: "https://www.linkedin.com/embed/feed/update/urn:li:ugcPost:7495212390024896512?collapsed=1", tags: ["ai"], name: "AI Video Assistant — Long Videos into Actionable Insights",
    blurb: "A generative AI assistant that turns long meetings, lectures, interviews and YouTube videos into something you can quickly understand and interact with, instead of watching for hours.",
    features: ["Audio and video transcription: converts speech into text", "AI summarization: concise summaries of long content", "Action items: extracts tasks that need to be completed", "Key decisions: identifies important decisions from the conversation", "Open questions: finds questions that were left unanswered", "Works with YouTube links and local video files"],
    stack: ["Python", "Generative AI / LLMs", "LangChain", "RAG", "Vector Search", "Speech-to-Text", "Prompt Engineering"], repo: "https://github.com/Krishnak64/AI-Video-Assistant" },
  { id: "flappybird", tags: ["ai"], name: "Flappy Bird AI — Deep Reinforcement Learning",
    blurb: "An intelligent Flappy Bird agent trained using Deep Q-Networks (DQN) that learns optimal actions through rewards, penalties, and continuous interaction with the game environment.",
    features: ["Deep Q-Network (DQN) based decision making", "Experience Replay for stable training", "Epsilon-Greedy exploration strategy", "Reward and penalty based learning", "Neural network based Q-value prediction", "Continuous environment interaction", "Progressive improvement through reinforcement learning"],
    stack: ["Python", "PyTorch", "Deep Reinforcement Learning", "DQN", "Experience Replay", "Neural Networks"], repo: "https://github.com/Krishnak64/FlappyBird_RL" },
  { id: "vybes", videoEmbed: "https://www.linkedin.com/embed/feed/update/urn:li:ugcPost:7402965149369724928?collapsed=1", tags: ["fs"], name: "Vybes — Social Media Platform", live: "https://vybe-s6ib.onrender.com/signin",
    blurb: "Production-grade social app with posts, reels, stories, likes, comments and follows, serving real users.",
    features: ["Real-time chat and notifications with Socket.IO", "JWT + bcrypt secure auth, protected endpoints", "MongoDB indexing for faster queries", "Media uploads managed via Cloudinary"],
    stack: ["React", "Node.js", "Express", "MongoDB", "Socket.IO", "JWT", "Cloudinary"], repo: "https://github.com/Krishnak64/1.vybe" },
  { id: "cora", tags: ["ai"], name: "CORA — Citation Network Paper Classification",
    blurb: "A graph machine learning project that classifies research papers into seven topics by combining paper word features with citation network structure using Random Forest and Graph Convolutional Networks.",
    features: ["Seven-class research paper topic classification", "Random Forest machine learning baseline", "Two-layer Graph Convolutional Network", "Citation network based message passing", "Graph and node feature analysis", "Traditional ML vs GNN comparison", "Research paper topic prediction", "Render and Streamlit deployment"],
    stack: ["Python", "Pandas", "NumPy", "Scikit-learn", "PyTorch", "PyTorch Geometric", "GCN", "Graph Neural Networks", "Streamlit"], repo: "https://github.com/Krishnak64/CORA-Project", live: "https://cora-project-kqgk.onrender.com/", demo: "https://coraprojectstr.streamlit.app/" },
  { id: "heart-disease", tags: ["ai"], name: "Heart Disease Prediction — ML",
    blurb: "A machine learning web application that predicts heart disease risk from clinical parameters using multiple classification models and an interactive Streamlit interface.",
    features: ["Exploratory Data Analysis and visualization", "Data cleaning and invalid value handling", "Categorical feature encoding", "Feature scaling using StandardScaler", "Comparison of 5 classification models", "KNN selected as the final prediction model", "Saved model and preprocessing pipeline", "Interactive real-time predictions"],
    stack: ["Python", "Pandas", "NumPy", "Scikit-learn", "Matplotlib", "Seaborn", "Streamlit"], repo: "https://github.com/Krishnak64/Heart_DiseasePrediction_ML", live: "https://heartpredictiondisease.streamlit.app/" },
  { id: "meethub", videoEmbed: "https://www.linkedin.com/embed/feed/update/urn:li:ugcPost:7444918903157477377?collapsed=1", tags: ["fs"], name: "MeetHub — Video Calling Platform",
    blurb: "A real-time video calling platform built with React that enables users to create and join video meetings with an interactive meeting experience.",
    features: ["Real-time video calling", "Create and join video meetings", "Interactive meeting interface", "Responsive React frontend", "Real-time communication", "Meeting room based architecture"],
    stack: ["React.js", "JavaScript", "HTML", "CSS", "WebRTC"], repo: "https://github.com/Krishnak64/MeetHub-Video-Call", live: "https://meethubvideocallfrontend.onrender.com/" },
  { id: "airbnb", tags: ["fs"], name: "Airbnb Clone — Major Project",
    blurb: "A full-stack Airbnb-inspired web application for browsing and managing property listings with authentication and complete CRUD functionality.",
    features: ["Property listing management", "Property details and browsing", "User authentication", "Create, update and delete listings", "Responsive web interface", "Full-stack CRUD functionality", "Dynamic property pages"],
    stack: ["JavaScript", "Node.js", "Express.js", "MongoDB", "HTML", "CSS"], repo: "https://github.com/Krishnak64/Airbnb-clone-working-Major-Project-", live: "https://airbnb-clone-working-major-project.onrender.com/" },
];
export const resumes = [
  { mode: "fs", title: "Full Stack Developer", file: "Krishna_Resume_FullStack.pdf", note: "MERN, REST APIs, real-time apps, DSA" },
  { mode: "ai", title: "AI / ML Engineer", file: "Krishna_Resume_AI-ML.pdf", note: "LLMs, computer vision, data science" },
];
export const stats = [["450+", "DSA problems solved"], ["6+", "apps shipped to production"], ["8.1", "CGPA, B.Tech IT (6th sem)"]];
